### PR TITLE
Add component split

### PR DESCRIPTION
**Pull request by CatherineTower**
Adds a function to create three images for red, blue, and green channels. `struct PixMapComponents` is a way to return the three `PixMapImage`s using one function.

Users will have to copy their individual `PixMapImage`s into separate objects to save them properly.

### CODE REVIEW

**Comment by Noah11012** [comment]
You don't need to dynamically allocate an `int`. Just create an int and pass it as a reference.

**Comment by Noah11012** [comment]
And if you must dynamically allocated and `int`, don't forget to free `error` in the `if` body at line 63.

**Comment by CatherineTower** [comment]
You're right, I wasn't thinking about that. I'll fix it once I'm home.

**Comment by Noah11012** [comment]
Make sure to pass `error` by reference.

**Comment by Noah11012** [comment]
I think most of these mistakes can be fixed early using a linter. One I recommend is Cppcheck. It's a linter for C/C++ projects. Another one is clang-tidy and while it's usually for C++, It can be used for C.

**Comment by CatherineTower** [comment]
Yeah, my issue there is that I went through and fixed it properly before realizing I was on the wrong branch. I'm still working on switching between devices, it's a learning curve.

**Pull request merged**
