### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by CatherineTower**
This mostly adds function documentation to the README file. There are several other commits that are changes that have already been made to the repository.

### CODE REVIEW

**Comment by Noah11012** [comment]
Thanks for your help with this project. You have been very helpful for the last few days. You may have noticed I haven't pushed much to this project for a bit now and that's because I'm working on another project called [Quick String](https://github.com/Noah11012/quick_string). I'm trying to get it to speed before I come back to this project. I'm also learning about algorithms so I can make more image filters in the future.

**Comment by CatherineTower** [comment]
Back on the 15th you posted on a dev.to article about projects looking for contributors, and I was looking for a first project I could work on. This ended up being ideal. I've not found a lot here on GitHub written in C, and this was still a new enough project that I could read through it in one sitting and know more or less what was going on. It ended up being a steep learning curve, between adapting to someone else's coding style, collaborating for the first time, and learning both Git and GitHub, but it's been incredibly rewarding already. I'm happy to continue development on this while you're working on other projects, I've just fallen into a bit of a lull where I'm not quite sure what to do next. I'll keep committing steadily, let me know if there's anything specific you'd like done or you'd not like done.

**Comment by Noah11012** [comment]
Well, I think the next phase we should start doing is adding more support for different shapes like circles and filters. There is a nice book called [The Pocket Handbook of Image Processing Algorithms in C](http://adaptiveart.eecs.umich.edu/2011/wp-content/uploads/2011/09/The-pocket-handbook-of-image-processing-algorithms-in-C.pdf). It has several cool image processing algorithm we can implement.

**Comment by CatherineTower** [comment]
I'll have a look at that.

**Pull request merged**
